name: "Synchron Brass"
developer: "Vienna Symphonic Library"
version: "1.0.0"
category: "brass"
website: "https://www.vsl.co.at/en/Synchron_Brass"

attribution:
  original_author: "Jared Thirsk"
  original_source: "https://github.com/jaredthirsk/cubase-expression-maps"
  original_license: "Unlicense"
  imported_by: "Cubby Articulations"
  import_date: "2025-01-28"

exports:
  - cubase

updated: "2025-01-28"

tags:
  - brass
  - orchestral
  - synchron
